classdef VectorMemory < handle
    properties
        positive_data;
        notpositive_data;
        default_value;
    end
    
    methods
        function obj = VectorMemory(in_default_value)
            obj.positive_data = repmat(in_default_value, 0);
            obj.notpositive_data = repmat(in_default_value, 0);
            obj.default_value = in_default_value;
        end
        function res = get_value(obj, in_position)
            [is_in_positive, position_num] = get_raw_position(in_position);
            if is_in_positive
                res = ...
                    get_raw_value(...
                        obj.positive_data, ...
                        position_num, ...
                        obj.default_value);    
            else
                res = ...
                    get_raw_value(...
                        obj.notpositive_data, ...
                        position_num, ...
                        obj.default_value);
            end
            function res = get_raw_value(...
                    in_vector, ...
                    in_position, ...
                    in_default_value)
                res = in_default_value;
                if in_position <= length(in_vector)
                    res = in_vector(in_position); 
                end
            end
        end
        function set_value(obj, in_position, in_value)
            [is_in_positive, position_num] = get_raw_position(in_position);
            if is_in_positive
                obj.positive_data = ...
                    insert_value(...
                        obj.positive_data, ...
                        position_num, ...
                        in_value, ...
                        obj.default_value);
            else
                obj.notpositive_data = ...
                    insert_value(...
                        obj.notpositive_data, ...
                        position_num, ...
                        in_value, ...
                        obj.default_value);                
            end
            function out_vector = insert_value(...
                    in_vector, ...
                    in_position, ...
                    in_value, ...
                    in_default_value)
                if in_position <= length(in_vector)
                    out_vector = in_vector;
                    out_vector(in_position) = in_value;
                elseif in_value == in_default_value
                    out_vector = in_vector;
                else
                    out_vector = ...
                        [in_vector, ...
                         repmat(in_default_value, ...
                                1, in_position-length(in_vector)-1), ...
                         cast(in_value, 'like', in_default_value)];
                end
            end
        end
    end
end

function [is_in_positive, position_num] = get_raw_position(in_position)
    if in_position >= 1
        is_in_positive = true;
        position_num = in_position;
    else
        is_in_positive = false;
        position_num = -in_position+1;
    end
end