function out_data = extend_by_doubling(...
        in_data, in_target_size, default_value)
    in_data_size = length(in_data);
    assert(in_data_size < in_target_size);
    true_target_size = in_target_size;
    if in_data_size ~= 0
        true_target_size = ...
            in_data_size*2^ceil(log(in_target_size/in_data_size)/log(2));    
    end
    out_data = ...
        BFMachinePac.MemoryTypes.extend_by_appending_needed(...
            in_data, true_target_size, default_value);
        %this is a nightmare...
        %cf. https://www.mathworks.com/matlabcentral/answers/399880-call-function-in-package-from-package
end