---
name: check_shell_scripts

'on':
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4

      - name: Install shellcheck
        run: |
          sudo apt-get install shellcheck
      - name: display shellcheck version
        run: |
          shellcheck --version
      - name: run check_shell_scripts
        run: |
          ./check_all_shell_scripts.sh
...
