---
name: cpp_static_analysis

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp_static_analysis.yml'
  pull_request:

env:
  build_path: ${{github.workspace}}/cpp/build

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        compiler: [g++-10, clang++-10, clang++-11, clang++-12]
        clang_tidy: [clang-tidy, clang-tidy-11]
        build_type: [Release, Debug]

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Install ${{matrix.compiler}}
        if: ${{ matrix.compiler != 'clang++-12' }}
        run: |
          sudo apt-get install ${{matrix.compiler}}

      - name: Install static analysis tools
        run: |
          sudo apt-get install ${{matrix.clang_tidy}}
          sudo apt-get install cppcheck
      - name: Create Build Environment
        run: cmake -E make_directory ${{env.build_path}}

      - name: Display versions
        run: |
          ${{matrix.compiler}} --version
          cmake --version
          cppcheck --version
          ${{matrix.clang_tidy}} --version

      - name: Configure CMake
        shell: bash
        working-directory: ${{env.build_path}}
        run: >
          cmake ../
          -D CMAKE_BUILD_TYPE=${{matrix.build_type}}
          -D CMAKE_CXX_COMPILER=${{matrix.compiler}}
          -D ENABLE_CLANG_TIDY=ON -D CLANG_TIDY_NAME=${{matrix.clang_tidy}}
          -D ENABLE_CPPCHECK=ON
          -D ENABLE_BOOST_TESTS=OFF -D ENABLE_TESTING=OFF

      - name: Build with ${{matrix.clang_tidy}} and cppcheck
        shell: bash
        working-directory: ${{env.build_path}}
        run: |
          cmake --build . --config ${{matrix.build_type}}
...
