name: cpp_build_macos_latest

on:
  push:
    paths: 
      - 'cpp/**'
      - '.github/workflows/cpp_build_macos_latest.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/cpp/build

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [g++-8, g++-9, g++-10, clang++]
    
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory $BUILD_DIR

    - name: Configure CMake
      shell: bash
      working-directory: $BUILD_DIR
      run: cmake ${{github.workspace}}/cpp -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D CMAKE_CXX_COMPILER=${{matrix.compiler}} -D ENABLE_BOOST_TESTS=OFF

    - name: Build with ${{matrix.compiler}}
      working-directory: $BUILD_DIR
      shell: bash
      run: |
        ${{matrix.compiler}} --version
        cmake --version
        cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: $BUILD_DIR
      shell: bash
      run: ctest -C $BUILD_TYPE
