name: cpp_build_ubuntu_latest

on:
  push:
    paths: 
      - 'cpp/**'
      - '.github/workflows/cpp_build_ubuntu_latest.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_PATH: ${{github.workspace}}/cpp/build

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-8, g++-9, g++-10, clang++-9, clang++-10]
    
    steps:
    - uses: actions/checkout@v2

    - name: Install ${{matrix.compiler}}
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install ${{matrix.compiler}}
    - name: Install boost
      run: |
        sudo apt-get install libboost-all-dev
    - name: Create Build Environment
      run: cmake -E make_directory ${{env.BUILD_PATH}}

    - name: Configure CMake
      shell: bash
      working-directory: ${{env.BUILD_PATH}}
      run: cmake ../ -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_CXX_COMPILER=${{matrix.compiler}}

    - name: Build with ${{matrix.compiler}}
      working-directory: ${{env.BUILD_PATH}}
      shell: bash
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{env.BUILD_PATH}}
      shell: bash
      run: ctest -C ${{env.BUILD_TYPE}}
