name: cpp_build_macos

on:
  workflow_dispatch:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp_build_macos.yml'
  schedule:
    - cron: '5 8 * * *'

env:
  BUILD_PATH: ${{github.workspace}}/cpp/build

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-9, g++-10, g++-11, clang++]
        os: [macos-10.15]
        build_type: [Release, Debug, RelWithDebInfo]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{env.BUILD_PATH}}
    - name: Configure CMake
      shell: bash
      working-directory: ${{env.BUILD_PATH}}
      run: cmake ../ -D CMAKE_BUILD_TYPE=${{matrix.build_type}} -D CMAKE_CXX_COMPILER=${{matrix.compiler}} -D ENABLE_BOOST_TESTS=OFF

    - name: Build with ${{matrix.compiler}}
      working-directory: ${{env.BUILD_PATH}}
      shell: bash
      run: |
        ${{matrix.compiler}} --version
        cmake --version
        cmake --build . --config ${{matrix.build_type}}
    - name: Test
      working-directory: ${{env.BUILD_PATH}}
      shell: bash
      run: ctest -C ${{matrix.build_type}}
