---
name: cpp_build_macos

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp_build_macos.yml'
  pull_request:
  schedule:
    - cron: '10 0 1,10,20 * 0'

env:
  build_path: ${{github.workspace}}/cpp/build

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-10, g++-11, clang++]
        os: [macos-11]
        build_type: [Release, Debug]

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac  # v4

      - name: Install Boost
        run: |
          brew install boost

      - name: Display versions
        run: |
          ${{matrix.compiler}} --version
          cmake --version

      - name: Create Build Environment
        run: cmake -E make_directory ${{env.build_path}}

      - name: Configure CMake
        shell: bash
        working-directory: ${{env.build_path}}
        run: >
          cmake ../
          -D CMAKE_BUILD_TYPE=${{matrix.build_type}}
          -D CMAKE_CXX_COMPILER=${{matrix.compiler}}
          -D ENABLE_BOOST_TESTS=ON

      - name: Build with ${{matrix.compiler}}
        working-directory: ${{env.build_path}}
        shell: bash
        run: |
          cmake --build . --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{env.build_path}}
        shell: bash
        run: ctest -C ${{matrix.build_type}}
...
