name: cpp_static_analysis

on:
  workflow_dispatch:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp_static_analysis.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_PATH: ${{github.workspace}}/cpp/build

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        compiler: [g++-10, clang++-10, clang++-11, clang++-12]
        clang_tidy: [clang-tidy, clang-tidy-11]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install ${{matrix.compiler}}
        sudo apt-get install ${{matrix.clang_tidy}}
        sudo apt-get install cppcheck
    - name: Create Build Environment
      run: cmake -E make_directory ${{env.BUILD_PATH}}

    - name: Configure CMake
      shell: bash
      working-directory: ${{env.BUILD_PATH}}
      run: cmake ../ -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_CXX_COMPILER=${{matrix.compiler}} -D ENABLE_CLANG_TIDY=ON -D CLANG_TIDY_NAME=${{matrix.clang_tidy}} -D ENABLE_CPPCHECK=ON -D ENABLE_BOOST_TESTS=OFF -D ENABLE_TESTING=OFF

    - name: Build with ${{matrix.clang_tidy}} and cppcheck analysis
      shell: bash
      working-directory: ${{env.BUILD_PATH}}
      run: |
        ${{matrix.compiler}} --version
        cppcheck --version
        ${{matrix.clang_tidy}} --version
        cmake -v --build . --config ${{env.BUILD_TYPE}}
