name: cpp_build_windows_latest

on:
  push:
    paths: 
      - 'cpp/**'
      - '.github/workflows/cpp_build_windows_latest.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_PATH: ${{github.workspace}}\cpp\build

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{env.BUILD_PATH}}

    - name: Configure CMake
      shell: bash
      working-directory: ${{env.BUILD_PATH}}
      run: cmake ../ -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D ENABLE_BOOST_TESTS=OFF

    - name: Build
      working-directory: ${{env.BUILD_PATH}}
      shell: bash
      run: cmake --build . --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{env.BUILD_PATH}}
      shell: bash
      run: ctest -C ${{env.BUILD_TYPE}}
