name: cpp_static_analysis

on:
  workflow_dispatch:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp_static_analysis.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  COMPILER_NAME: g++-10
  BUILD_PATH: ${{github.workspace}}/cpp/build

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install ${{env.COMPILER_NAME}}
        sudo apt-get install clang-tidy
        sudo apt-get install cppcheck
    - name: Create Build Environment
      run: cmake -E make_directory ${{env.BUILD_PATH}}

    - name: Configure CMake
      shell: bash
      working-directory: ${{env.BUILD_PATH}}
      run: cmake ../ -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_CXX_COMPILER=${{env.COMPILER_NAME}} -D ENABLE_CLANG_TIDY=ON -D ENABLE_CPPCHECK=ON -D ENABLE_BOOST_TESTS=OFF -D ENABLE_TESTING=OFF

    - name: Build with clang-tidy and cppcheck analysis
      shell: bash
      working-directory: ${{env.BUILD_PATH}}
      run: |
        ${{env.COMPILER_NAME}} --version
        cppcheck --version
        clang-tidy --version
        cmake --build . --config ${{env.BUILD_TYPE}}
