name: static_analysis

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  COMPILER_NAME: g++-10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install $COMPILER_NAME
        sudo apt-get install clang-tidy-10
        sudo apt-get install cppcheck
    - name: Create Build Environment
      working-directory: ${{github.workspace}}/cpp
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/cpp/build
      run: cmake ../ -DCMAKE_BUILD_TYPE=$BUILD_TYPE -D CMAKE_CXX_COMPILER=$COMPILER_NAME -D ENABLE_CLANG_TIDY=ON -D ENABLE_CPPCHECK=ON -D ENABLE_BOOST_TESTS=OFF -D ENABLE_TESTING=OFF

    - name: Build with clang-tidy and cppcheck analysis
      shell: bash
      working-directory: ${{github.workspace}}/cpp/build
      run: |
        pwd
        cat ../.clang-tidy
        cppcheck --version
        clang-tidy --version
        clang-tidy --dump-config
        cmake --build . -v --config $BUILD_TYPE
